github: skip dependency update when gemset.nix is invalid

diff --git a/.github/workflows/daily-update.yml b/.github/workflows/daily-update.yml
--- a/.github/workflows/daily-update.yml
+++ b/.github/workflows/daily-update.yml
@@ -57,6 +57,12 @@ jobs:
             rm -f gemset.nix Gemfile.lock
             nix-shell -p bundix --run "bundix -l"
             nix-shell -p nixfmt-rfc-style --run "nixfmt gemset.nix"
+
+            if ! grep -q 'source =' gemset.nix ; then
+              echo "Invalid $pkg/gemset.nix: missing sources, skipping"
+              popd
+              continue
+            fi
             
             git add gemset.nix Gemfile.lock
 
